Remove dependency on runtime-fmt to fix the Rust Nightly build
error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:194:33
    |
194 |         let pieces = self.inner.pieces();
    |                                 ^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime `'s` as defined on the impl at 174:6...
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:174:6
    |
174 | impl<'s, T: FormatArgs> PreparedFormat<'s, T> {
    |      ^^
note: ...so that the type `Parsed<'s, DelayedParse<T>>` is not borrowed for too long
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:194:22
    |
194 |         let pieces = self.inner.pieces();
    |                      ^^^^^^^^^^
    = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the expression is assignable
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:200:58
    |
200 |             Some(ref fmt) => Arguments::new_v1_formatted(&pieces, &args, fmt),
    |                                                          ^^^^^^^
    = note: expected `&[&'static str]`
               found `&[&str]`

error[E0495]: cannot infer an appropriate lifetime for autoref due to conflicting requirements
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:265:33
    |
265 |         let pieces = self.inner.pieces();
    |                                 ^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime `'s` as defined on the impl at 245:6...
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:245:6
    |
245 | impl<'s> FormatBuf<'s> {
    |      ^^
note: ...so that the type `Parsed<'s, ImmediateParse<'s>>` is not borrowed for too long
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:265:22
    |
265 |         let pieces = self.inner.pieces();
    |                      ^^^^^^^^^^
    = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the expression is assignable
   --> /home/at/.cargo/git/checkouts/runtime-fmt-9426a9c114311a5e/4448167/src/lib.rs:267:58
    |
267 |             Some(ref fmt) => Arguments::new_v1_formatted(&pieces, &self.inner.args, fmt),
    |                                                          ^^^^^^^
    = note: expected `&[&'static str]`
               found `&[&str]`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0495`.
error: could not compile `runtime-fmt`.